twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        author_name: '%env(AUTHOR_NAME)%'
        author_username: '%env(AUTHOR_USERNAME)%'
        author_website: '%env(AUTHOR_WEBSITE)%'
        git_link: '%env(GIT_LINK)%'
        app_name: '%env(APP_NAME)%'

when@test:
    twig:
        strict_variables: true
